## Travis CI Integration

language: c

# Make sure build dependencies are installed.
install:
 - sudo add-apt-repository -y ppa:directhex/monoxide
 - sudo apt-get update -qq
 - sudo apt-get install -qq mono-devel mono-gmcs cli-common-dev
 - mozroots --import --sync
cache: apt

# Run the build script
script:
 - ./build.sh
